{
    'name': 'EGT Quotation Rent Report',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Custom Quotation Rent Report for EGT',
    'description': 'Custom report template for EGT quotation rentals',
    'depends': ['sale', 'purchase'],
    'data': [
        'report/bg_rent_order.xml',
        'report/egt_report_quotation_sale.xml',
        'report/quotation_rent_report.xml',
        'report/quotation_sale_report.xml',
        'report/quatiation_purchase.xml',
        'report/quotation_rent_ge_gm.xml',
        'report/egt_report_quotation_rent.xml',
        'views/egt_report_quotation_sale_premier.xml',
        'views/egt_report_quotation_sale_general_premier.xml',
    ],
        'assets': {
        'web.assets_backend': [
            'egt_report/static/src/img/Picture1.jpg',
            'egt_report/static/src/img/Picture2.jpg',
            'egt_report/static/src/img/Picture3.jpg',
            'egt_report/static/src/img/Picture4.jpg',
            'egt_report/static/src/img/Picture5.jpg',
            'egt_report/static/src/img/Picture6.jpg',
            'egt_report/static/src/img/Picture7.jpg',
            'egt_report/static/src/img/Picture8.jpg',
            'egt_report/static/src/img/Picture9.jpg',
            'egt_report/static/src/img/Picture10.jpg',
            'egt_report/static/src/img/Picture11.jpg',
            'egt_report/static/src/img/Picture12.jpg',
            'egt_report/static/src/img/Picture13.jpg',
            'egt_report/static/src/img/Picture14.jpg',
            'egt_report/static/src/img/Picture15.jpg',
            'egt_report/static/src/img/Picture16.jpg',
            'egt_report/static/src/img/Picture17.jpg',
            'egt_report/static/src/img/Picture18.jpg',
            'egt_report/static/src/img/Picture19.jpg',
            'egt_report/static/src/img/Picture20.jpg',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}